### PR TITLE
Fix vertical centering of input

### PR DESCRIPTION
**Pull request by peterzhu2118**
Fixes problems of uncentered vertical input. Shown better in the images below.

Before:

After:

### CODE REVIEW

**Comment by m4tx** [comment]
It think that setting `margin-top` and `margin-bottom` both to `5px` looks a bit better, since the text is aligned with the tokens:
screenshot from 2018-05-05 12-12-40
If you agree, please change the PR and I'll merge it!

**Comment by peterzhu2118** [comment]
@m4tx I've updated it to 5px. I've also updated the LESS file. Take a look at it and let me know if other changes are needed.

**Comment by peterzhu2118** [comment]
Actually, upon further inspection and applying #2, it's better to leave it at 6px of margin. Here is the comparison:

5px:
5px

6px:
6px

Notice how the 5px version is slightly lower than the other Semantic UI elements.

**Comment by m4tx** [comment]
Okay, I think it makes sense. Merging both PRs. Thanks for the contribution!

**Pull request merged**
